### ISSUE TITLE
Could you release the "main" fix in package.json

### ISSUE THREAD

**Issue by seancurtis** [jbovenschen/storybook-addon-a11y#3]
Got errors when adding checkA11y to one of my stories. Looks like you've already fixed the entry point, but not released it yet. Could you do a quick release for that fix?

**Comment by jbovenschen** [comment]
Done, just published a 0.0.4 version. Did not published it yet because we are using it currently within our own storybook yet.

Hope that you can provide us with things we can improve, and issues you encounter when using it.
